version: "3"
services:
  app:
    build: .
    ports:
      - "7899:7899"
    restart: always
    volumes:
      - .:/app
    container_name: kratos_payment_api
    entrypoint: ["gunicorn", "--bind", "0.0.0.0:7899", "src.wsgi"]
    depends_on:
      - db

  db:
    image: postgres:15
    env_file: .env
    ports:
      - "5414"
    container_name: kratos_payment_postgres
