version: "3"
services:
  server:
    build: .
    ports:
      - "7899:7899"
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    container_name: app_kratos_payment
    depends_on:
      - db
    networks:
      - nginx

  db:
    image: postgres:15
    env_file: .env
    ports:
      - "5414:5432"
    container_name: kratos_payment_postgre
    networks:
      - nginx

  django:
    build: .
    volumes:
      - .:/app
    entrypoint: [ "python3", "manage.py" ]

  pip:
    build: .
    volumes:
      - .:/app
    entrypoint: [ "pip" ]
  
  nginx:
    image: nginx:latest
    container_name: nginx_ssl
    ports:
      - "454:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - server
    networks:
      - nginx

volumes:
  postgres_data:
  static_volume:
  media_volume:
  
networks:
  nginx:
    driver: bridge

